defaults: &defaults
  docker:
    - image: circleci/node:10-browsers

restore_dependencies: &restore_dependencies
  restore_cache:
    keys:
       - v1-dependencies-{{ checksum "yarn.lock" }}
       # Fallback to using the latest cache if no exact match is found.
       - v1-dependencies-

save_dependencies: &save_dependencies
  save_cache:
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum "yarn.lock" }}

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - <<: *restore_dependencies
      - run: yarn install
      - <<: *save_dependencies

      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - run: yarn coverage

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
